// Generated by CoffeeScript 1.6.3
(function() {
  var Enhance, helpers;

  helpers = require('./helpers');

  Enhance = (function() {
    return function(options) {
      var defaults, exports, isMobileDevice, render;
      defaults = {
        host: null,
        suffix: '@2x',
        phoneBreakpoint: 480,
        tabletBreakpoint: 1024,
        tabletAsMobile: false
      };
      options = helpers.merge(defaults, options);
      isMobileDevice = function() {
        var breakpoint, mobileDevice;
        mobileDevice = options.tabletAsMobile ? 'tablet' : 'phone';
        breakpoint = options["" + mobileDevice + "Breakpoint"];
        return typeof window.matchMedia === "function" ? window.matchMedia("only screen and (max-width: " + breakpoint + "px)").matches : void 0;
      };
      render = function(src, opts) {
        var regexp;
        if (options.render != null) {
          return typeof options.render === "function" ? options.render(helpers.merge({
            src: src
          }, options, opts, {
            helpers: helpers
          })) : void 0;
        } else {
          regexp = new RegExp(/(.jpe?g|.png|.gif|.ti?ff?)/i);
          if (helpers.isHiDPI()) {
            src = src.replace(regexp, "" + options.suffix + "$1");
          }
          return helpers.joinURIComponents(options.host, src);
        }
      };
      return exports = {
        isHiDPI: helpers.isHiDPI,
        render: render,
        isMobileDevice: isMobileDevice
      };
    };
  })();

  if (typeof window !== "undefined" && window !== null) {
    window.Enhance = Enhance;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Enhance;
  }

}).call(this);
