// Generated by CoffeeScript 1.6.3
(function() {
  var Enhance, _;

  _ = require('./lodash-ext');

  Enhance = (function() {
    return function(options) {
      var defaults, exports, helpers, isHiDPI, render;
      defaults = {
        host: null,
        suffix: '@2x'
      };
      options = _.merge(defaults, options);
      isHiDPI = function(ratio) {
        var query;
        if (ratio == null) {
          ratio = 1.3;
        }
        query = "only screen and (-moz-min-device-pixel-ratio: " + ratio + "),         only screen and (-o-min-device-pixel-ratio: " + (ratio * 2) + "/2),         only screen and (-webkit-min-device-pixel-ratio: " + ratio + "),         only screen and (min-device-pixel-ratio: " + ratio + "),         only screen and (min-resolution: " + ratio + "dppx)";
        if (window.devicePixelRatio > ratio) {
          return true;
        }
        if (typeof window.matchMedia === "function" ? window.matchMedia(query).matches : void 0) {
          return true;
        }
        return false;
      };
      helpers = {
        _: _,
        isHiDPI: isHiDPI
      };
      render = function(src, opts) {
        var regexp;
        if (options.render != null) {
          return typeof options.render === "function" ? options.render(_.merge({
            src: src
          }, options, opts, helpers)) : void 0;
        } else {
          regexp = new RegExp(/(.jpe?g|.png|.gif|.ti?ff?)/i);
          if (isHiDPI()) {
            src = src.replace(regexp, "" + options.suffix + "$1");
          }
          return _.joinURIComponents(options.host, src);
        }
      };
      return exports = {
        isHiDPI: isHiDPI,
        render: render
      };
    };
  })();

  module.exports = Enhance;

}).call(this);
