// Generated by CoffeeScript 1.6.3
(function() {
  var helpers,
    _this = this,
    __slice = [].slice;

  helpers = {
    joinURIComponents: function() {
      var components, leadingSlashes, rawComponents, _ref;
      rawComponents = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      leadingSlashes = ((_ref = rawComponents[0]) != null ? _ref.match(/^[\/]{1,2}/) : void 0) || '';
      components = [];
      rawComponents.forEach(function(rawComponent) {
        if (rawComponent != null) {
          return components = components.concat(helpers.trim(rawComponent, '/').split(/\/(?!\/)/));
        }
      });
      return leadingSlashes + components.join('/');
    },
    trim: function(string, characters) {
      var regexp;
      if (characters == null) {
        characters = '\\s';
      }
      regexp = new RegExp("^[" + characters + "]+|[" + characters + "]+$", 'g');
      return string.replace(regexp, '');
    },
    merge: function() {
      var k, obj, objs, target, v, _i, _len;
      objs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      target = {};
      for (_i = 0, _len = objs.length; _i < _len; _i++) {
        obj = objs[_i];
        for (k in obj) {
          v = obj[k];
          target[k] = v;
        }
      }
      return target;
    },
    isHiDPI: function(ratio) {
      var query;
      if (ratio == null) {
        ratio = 1.3;
      }
      query = "only screen and (-moz-min-device-pixel-ratio: " + ratio + "),       only screen and (-o-min-device-pixel-ratio: " + (ratio * 2) + "/2),       only screen and (-webkit-min-device-pixel-ratio: " + ratio + "),       only screen and (min-device-pixel-ratio: " + ratio + "),       only screen and (min-resolution: " + ratio + "dppx)";
      if (window.devicePixelRatio > ratio) {
        return true;
      }
      if (typeof window.matchMedia === "function" ? window.matchMedia(query).matches : void 0) {
        return true;
      }
      return false;
    }
  };

  module.exports = helpers;

}).call(this);
